import { useEffect, useState } from 'react';
import type { Session } from '@supabase/supabase-js';
import { Bar, BarChart, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { IconChartBar, IconLink, IconRefresh, IconTrendingUp } from '@tabler/icons-react';
import { loadConnectionAnalytics } from './api';
import type { connectionAnalytics } from '../../api/src/connectionAnalytics';
import './connectionAnalytics.css';

type Report = ReturnType<typeof connectionAnalytics>;
type Props = { session?: Session | null; viewerId: string; start?: string; end?: string; source: string; audience?: 'marketing-agent' | 'sales-agent' | 'management' };
const percent = (value: number | null) => value === null ? 'Not available' : `${value}%`;
const tooltipStyle = { background: 'var(--surface)', border: '1px solid var(--border)', color: 'var(--text)', borderRadius: 10 };
function Bars({data, value = 'count', label = 'Leads', color = 'var(--accent)'}: {data: Array<{name:string; [key:string]: unknown}>; value?: string; label?: string; color?: string}) {
  return data.length ? <ResponsiveContainer width="100%" height={Math.max(200,Math.min(480,data.length*42))}><BarChart data={data} layout="vertical" margin={{left:8,right:20,bottom:6}}><CartesianGrid stroke="var(--border)" horizontal={false}/><XAxis type="number" allowDecimals={false} tick={{fill:'var(--muted)',fontSize:11}}/><YAxis type="category" dataKey="name" width={112} tick={{fill:'var(--text)',fontSize:12}}/><Tooltip contentStyle={tooltipStyle}/><Bar dataKey={value} name={label} fill={color} radius={[0,5,5,0]} isAnimationActive={false}/></BarChart></ResponsiveContainer> : <p className="ca-empty">No recorded results in this period.</p>;
}
export function ConnectionAnalyticsPanel({session,viewerId,start,end,source,audience='management'}:Props) {
  const [report,setReport] = useState<Report>(); const [error,setError] = useState(''); const [reload,setReload] = useState(0);
  const [agent,setAgent] = useState('all');
  useEffect(() => {
    let current = true; setReport(undefined); setError(''); setAgent(audience === 'marketing-agent' ? `marketing:${viewerId}` : audience === 'sales-agent' ? `sales:${viewerId}` : 'all');
    if (!session) return;
    loadConnectionAnalytics(session,{viewerId,start,end:end ?? new Date().toISOString(),source,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone}).then((value) => {if(current)setReport(value);}).catch((reason) => {if(current)setError(reason instanceof Error ? reason.message : 'Could not load connection analytics.');});
    return () => {current=false;};
  },[session,viewerId,start,end,source,reload,audience]);
  if (!session) return null;
  if (!report) return <section className="connection-analytics ca-state" aria-live="polite"><p>{error || 'Loading connection analytics…'}</p>{error && <button onClick={()=>setReload(reload+1)}>Retry analytics</button>}</section>;
  const agents = [...report.marketingAgents.map((row)=>({...row,key:`marketing:${row.id}`,label:`Marketing · ${row.name}`})),...report.salesAgents.map((row)=>({...row,key:`sales:${row.id}`,label:`Sales · ${row.name}`}))];
  const selected = agents.find((row)=>row.key===agent);
  const personal = audience === 'marketing-agent' || audience === 'sales-agent';
  const daily = personal ? selected?.trend ?? [] : selected?.trend ?? report.daily.map((row)=>({...row,unknown:row.unknown+row.unqualified}));
  const personalRow = audience === 'marketing-agent' ? report.marketingAgents.find((row) => row.id === viewerId) : report.salesAgents.find((row) => row.id === viewerId);
  const count = audience === 'marketing-agent' ? personalRow?.found ?? 0 : report.totals.periodConnections;
  const label = audience === 'marketing-agent' ? 'My leads found' : 'My first connections';
  const title = personal ? audience === 'marketing-agent' ? 'My lead impact' : 'My connection results' : 'Connections & lead quality';
  return <section className="connection-analytics" aria-label="Research and connection analytics">
    <header className="ca-heading"><div><p className="ca-eyebrow">RESEARCH TO RELATIONSHIPS</p><h2>{title}</h2><p>{personal ? 'Your recorded work and the outcomes of leads in your scope.' : 'Recorded activity, attributed to the people who did the work.'}</p></div><button onClick={()=>setReload(reload+1)} aria-label="Refresh connection analytics"><IconRefresh size={18}/>Refresh</button></header>
    <div className="ca-metrics"><article><IconLink/><span>{personal ? label : 'First connections in period'}</span><strong>{count}</strong><small>{audience === 'marketing-agent' ? 'Saved usable contact details' : 'Each lead counted once'}</small></article><article><IconTrendingUp/><span>Connections per day</span><strong>{personal ? personalRow?.dailyAverage ?? 'Not available' : report.totals.dailyAverage ?? 'Not available'}</strong><small>Across {report.days} calendar days, including zero days</small></article><article><IconChartBar/><span>{audience === 'marketing-agent' ? 'Connection rate from my leads' : 'Assigned-lead connection rate'}</span><strong>{percent(personal ? personalRow?.rate ?? null : report.totals.rate)}</strong><small>{personal ? `${personalRow?.connected ?? 0} connected / ${personalRow?.assigned ?? 0} leads assigned in period` : `${report.totals.connected} connected / ${report.totals.assigned} leads assigned in period`}</small></article></div>
    <div className="ca-grid">
      {(audience !== 'sales-agent') && <article className="ca-card"><h3>Research lead comparison</h3><p>Shared queue arrivals by project type</p><Bars data={report.categories}/>{report.excludedCategories>0 && <p className="ca-footnote">{report.excludedCategories} SEO or unclassified arrivals are outside these four categories.</p>}</article>}
      {audience === 'marketing-agent' && <article className="ca-card"><h3>App research: received vs found</h3><p>Workload by day. Found leads may have arrived in an earlier period.</p><ResponsiveContainer width="100%" height={220}><BarChart data={report.daily}><CartesianGrid stroke="var(--border)" vertical={false}/><XAxis dataKey="day" minTickGap={40} tick={{fill:'var(--muted)',fontSize:11}}/><YAxis allowDecimals={false} tick={{fill:'var(--muted)',fontSize:11}}/><Tooltip contentStyle={tooltipStyle}/><Legend/><Bar dataKey="received" name="Received · shared queue" fill="var(--accent)" isAnimationActive={false}/><Bar dataKey="found" name="Found · your work" fill="var(--success)" isAnimationActive={false}/></BarChart></ResponsiveContainer></article>}
      <article className={`ca-card ${personal ? 'ca-wide' : ''}`}><div className="ca-card-heading"><div><h3>{audience === 'marketing-agent' ? 'Sales connections from my leads' : 'Daily first connections'}</h3><p>{audience === 'marketing-agent' ? 'Successful Sales conversations credited to the leads you supplied.' : 'Successful Sales conversations credited to the Sales Agent who made the first connection.'}</p></div>{!personal && <label>Show trend<select value={agent} onChange={(event)=>setAgent(event.target.value)}><option value="all">All permitted connections</option>{agents.map((row)=><option key={row.key} value={row.key}>{row.label}</option>)}</select></label>}</div>
        <ResponsiveContainer width="100%" height={260}><LineChart data={daily} margin={{top:16,right:20,left:0,bottom:6}}><CartesianGrid stroke="var(--border)" strokeDasharray="3 3"/><XAxis dataKey="day" minTickGap={40} tick={{fill:'var(--muted)',fontSize:11}}/><YAxis allowDecimals={false} tick={{fill:'var(--muted)',fontSize:11}}/><Tooltip contentStyle={tooltipStyle}/><Legend/><Line dataKey="connected" name="First connections" stroke="var(--accent)" strokeWidth={3} dot={daily.length<32} isAnimationActive={false}/><Line dataKey="mql" name="MQL at connection" stroke="var(--success)" dot={false} isAnimationActive={false}/><Line dataKey="sql" name="SQL at connection" stroke="var(--accent-blue)" dot={false} isAnimationActive={false}/><Line dataKey="unknown" name="Not qualified / not available" stroke="var(--muted)" strokeDasharray="4 4" dot={false} isAnimationActive={false}/></LineChart></ResponsiveContainer>
        <p className="ca-footnote">{selected && !personal ? `${selected.name}: ${selected.periodConnections} connections, ${selected.dailyAverage ?? 'Not available'} per day. ` : ''}Dates use {report.timezone}. Repeated conversations do not increase first-connection totals.</p>
      </article>
      {audience === 'management' && report.marketing && <><article className="ca-card"><h3>Leads found by marketer</h3><p>First usable contact details saved in this period</p><Bars data={report.marketingAgents} value="found" label="Found" color="var(--success)"/></article><article className="ca-card ca-wide"><h3>App research: received vs found</h3><p>Workload by day. Found leads may have arrived in an earlier period.</p><ResponsiveContainer width="100%" height={240}><BarChart data={report.daily}><CartesianGrid stroke="var(--border)" vertical={false}/><XAxis dataKey="day" minTickGap={40} tick={{fill:'var(--muted)',fontSize:11}}/><YAxis allowDecimals={false} tick={{fill:'var(--muted)',fontSize:11}}/><Tooltip contentStyle={tooltipStyle}/><Legend/><Bar dataKey="received" name="Received · shared queue" fill="var(--accent)" isAnimationActive={false}/><Bar dataKey="found" name="Found · your scope" fill="var(--success)" isAnimationActive={false}/></BarChart></ResponsiveContainer></article></>}
      {audience === 'management' && ([['Marketing-supplied leads',report.marketingAgents],['Sales connection performance',report.salesAgents]] as const).filter(([,rows])=>rows.length>0).map(([title,rows])=><article className="ca-card" key={title}><h3>{title}</h3><p>Connected leads from assignments made in the selected period</p><Bars data={rows} value="connected" label="Connected"/><div className="ca-table-scroll"><table><thead><tr><th>Agent</th><th>Assigned</th><th>Connected</th><th>Rate</th><th>Attempted, not connected</th><th>No recorded attempt</th><th>Connected by another agent</th></tr></thead><tbody>{rows.map((row)=><tr key={row.id}><th>{row.name}</th><td>{row.assigned}</td><td>{row.connected}</td><td>{percent(row.rate)}</td><td>{row.attempted}</td><td>{row.notAttempted}</td><td>{row.connectedByOther}</td></tr>)}</tbody></table></div><p className="ca-footnote">Reassigned leads can appear in multiple Sales denominators. Company totals count each lead once.</p></article>)}
      {audience !== 'management' && <article className="ca-card"><h3>{audience === 'marketing-agent' ? 'Lost leads from my work' : 'Lost leads by reason'}</h3><p>Latest recorded Lost / Not interested event per lead in this period</p><Bars data={report.losses} color="var(--danger)"/></article>}
      {audience === 'management' && <article className="ca-card"><h3>Marketing → Sales connections</h3><p>Who supplied the lead and who made its first connection</p>{report.handoffs.length ? <div className="ca-table-scroll"><table><thead><tr><th>Marketer</th><th>Sales agent</th><th>Connected</th></tr></thead><tbody>{report.handoffs.map((row,index)=><tr key={index}><th>{row.marketer}</th><td>{row.salesperson}</td><td>{row.connected}</td></tr>)}</tbody></table></div> : <p className="ca-empty">No first connections recorded in this period.</p>}</article>}
    </div>
    {(report.missing.foundEvidence+report.missing.qualification+report.missing.lossDates)>0 && <details className="ca-evidence"><summary>Historical data coverage</summary><p>{report.missing.foundEvidence} researched leads have no recorded first-found date or finder. {report.missing.qualification} connections have no qualification snapshot. {report.missing.lossDates} lost leads have no recorded loss date. Missing evidence is not assigned a guessed date or agent.</p></details>}
  </section>;
}
