import { FormEvent, useEffect, useMemo, useState } from 'react';
import { IconArrowLeft, IconAt, IconCalendarEvent, IconCheck, IconChevronDown, IconCircleCheck, IconClock, IconEdit, IconExternalLink, IconFlag, IconHistory, IconMail, IconMessage, IconNotes, IconPhone, IconPlus, IconRefresh, IconTargetArrow, IconUser, IconX } from '@tabler/icons-react';
import { canEditLeadDetails, canFlagIncorrectLead, leadCategoryLabels, leadCategoryOptions, salesIncorrectReportCount, sourceOptions, type Lead, type User } from './domain';
import { canRestore, focusForHealth, healthLabel, isRemoteCrmId, validateContactMethod, type ContactHealth, type LeadContactMethod } from './leadWorkflow';
import type { Session } from '@supabase/supabase-js';
import { addRemoteContactMethod, assessRemoteContactMethod, loadRemoteActivityHistory, loadRemoteContactMethods, logRemoteSalesActivity, restoreRemoteContactMethod } from './api';

const healthOptions: ContactHealth[] = ['verified', 'incorrect', 'wrong_person', 'reception_gatekeeper', 'do_not_contact'];
const firstMethods = (lead: Lead): LeadContactMethod[] => lead.discoveredContactMethods ? lead.discoveredContactMethods.map((method, index) => ({ ...method, id: `${lead.id}-method-${index}`, health: 'unverified', focus: 'active' })) : [
  ...(lead.phone ? [{ id: `${lead.id}-phone`, type: 'phone' as const, value: lead.phone, health: 'unverified' as const, focus: 'active' as const }] : []),
  ...(lead.email ? [{ id: `${lead.id}-email`, type: 'email' as const, value: lead.email, health: 'unverified' as const, focus: 'active' as const }] : []),
];

function actionIcon(type: string) { return type === 'email' ? <IconMail size={16} /> : type === 'sms' ? <IconMessage size={16} /> : <IconPhone size={16} />; }
function format(value: string) { return new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' }).format(new Date(value)); }
function hasMarketingControl(user: User) { return user.role === 'marketer' || user.role === 'admin' || (user.role === 'manager' && user.department === 'marketing'); }
function contactValue(method: LeadContactMethod) {
  if (method.type === 'email') return method.value;
  const digits = method.value.replace(/\D/g, '');
  if (digits.length === 10) return `(${digits.slice(0,3)}) ${digits.slice(3,6)}-${digits.slice(6)}`;
  if (digits.length === 11 && digits.startsWith('1')) return `+1 (${digits.slice(1,4)}) ${digits.slice(4,7)}-${digits.slice(7)}`;
  return method.value;
}
const outcomeLabels: Record<string, string> = { connected: 'Connected', no_answer: 'No answer', voicemail: 'Voicemail', busy: 'Busy', callback_requested: 'Callback requested', email_sent: 'Email sent', replied: 'Replied', meeting_booked: 'Meeting booked', not_interested: 'Not interested', other: 'Other', recorded: 'Recorded' };
type HistoryItem = { id: string; at: string; type: string; outcome: string; method?: string; note?: string; actorId?: string; followUpAt?: string; followUpPurpose?: string };
const localHistory = (lead: Lead): HistoryItem[] => [...lead.activities].sort((a,b) => Date.parse(b.at)-Date.parse(a.at)).map((item) => ({ id:item.id, at:item.at, type:item.kind, outcome:'recorded', note:item.body, actorId:item.actorId }));

export function LeadWorkspace({ lead, viewer, workspaceUsers, session, onBack, onStatus, onQualification, onReassign, onEditDetails, onReportIncorrect, onDecision }: { lead: Lead; viewer: User; workspaceUsers: User[]; session?: Session; onBack: () => void; onStatus: (lead: Lead, status: Lead['status'], options?: { persist?: boolean }) => void; onQualification: (lead: Lead, qualification: Lead['qualification']) => void; onReassign: (lead: Lead, event: FormEvent<HTMLFormElement>) => void; onEditDetails: (lead: Lead, event: FormEvent<HTMLFormElement>) => void; onReportIncorrect: (lead: Lead, event: FormEvent<HTMLFormElement>) => void; onDecision: (lead: Lead, decision: 'confirmed_incorrect' | 'rejected' | 'merge_duplicate') => void; }) {
  const [methods, setMethods] = useState<LeadContactMethod[]>(() => firstMethods(lead));
  const [followUps, setFollowUps] = useState(lead.followUps);
  const [tab, setTab] = useState<'overview' | 'history'>('overview');
  const [activityOpen, setActivityOpen] = useState(false);
  const [activityMethodId, setActivityMethodId] = useState<string>();
  const [contactOpen, setContactOpen] = useState(false);
  const [editOpen, setEditOpen] = useState(false);
  const [flagOpen, setFlagOpen] = useState(false);
  const [notice, setNotice] = useState('');
  const [history, setHistory] = useState<HistoryItem[]>(() => localHistory(lead));
  const active = methods.filter((method) => method.focus === 'active');
  const secondary = methods.filter((method) => method.focus === 'secondary');
  const removed = methods.filter((method) => method.focus === 'removed');
  const sales = viewer.role === 'sales_agent';
  const marketingControl = hasMarketingControl(viewer);
  const canManage = sales || viewer.role === 'manager' || viewer.role === 'admin' || viewer.role === 'marketer';
  const canCorrectQualification = viewer.role === 'manager' || viewer.role === 'admin';
  const canEdit = canEditLeadDetails(viewer, lead, workspaceUsers);
  const canFlag = canFlagIncorrectLead(viewer, lead, workspaceUsers) && !lead.routingPaused && !lead.incorrectReports.some((report) => report.reporterId === viewer.id);
  const salesFlagCount = salesIncorrectReportCount(lead.incorrectReports);
  const nextFollowUp = [...followUps].filter((item) => item.status === 'open').sort((a,b) => Date.parse(a.dueAt)-Date.parse(b.dueAt))[0];
  const latestActivity = history[0];
  const primaryMethod = active.find((method) => method.health === 'verified') ?? active[0] ?? secondary[0];

  useEffect(() => { setMethods(firstMethods(lead)); setFollowUps(lead.followUps); setHistory(localHistory(lead)); setTab('overview'); window.scrollTo({ top: 0, behavior: 'instant' }); }, [lead.id]);
  useEffect(() => {
    if (!session || !isRemoteCrmId(lead.id)) return;
    let alive = true;
    void Promise.all([loadRemoteContactMethods(session, lead.id), loadRemoteActivityHistory(session, lead.id)]).then(([methodResult, historyResult]) => {
      if (!alive) return;
      const remoteMethods = methodResult.contactMethods.flatMap((item) => {
        const method = item.contact_methods;
        return method ? [{ id: method.id, type: method.method_type, value: method.value, label: method.label ?? undefined, health: item.health, focus: item.focus, reason: item.assessment_reason ?? undefined, restricted: Boolean(method.globally_restricted), lastAttemptAt: item.last_assessed_at ?? undefined }] : [];
      });
      if (remoteMethods.length) setMethods(remoteMethods);
      setHistory(historyResult.activities.map((item) => ({ id: item.id, at: item.occurred_at ?? item.created_at, type: item.type, outcome: item.outcome ?? 'recorded', method: item.contact_methods?.value, note: item.body ?? undefined, actorId: item.actor_id ?? undefined })));
    }).catch((error: unknown) => { if (alive) setNotice(error instanceof Error ? `CRM data could not load: ${error.message}` : 'CRM data could not load.'); });
    return () => { alive = false; };
  }, [session, lead.id]);

  function assess(method: LeadContactMethod, health: ContactHealth) {
    if (!canManage) return;
    const focus = focusForHealth(health);
    setMethods((items) => items.map((item) => item.id === method.id ? { ...item, health, focus, restricted: health === 'do_not_contact' } : item));
    if (session && isRemoteCrmId(lead.id) && isRemoteCrmId(method.id)) void assessRemoteContactMethod(session, lead.id, method.id, { health }).catch((error: unknown) => setNotice(error instanceof Error ? error.message : 'CRM could not update this contact method.'));
    setNotice(focus === 'removed' ? `${method.value} was moved out of your active focus.` : `${method.value} was updated.`);
  }
  function restore(method: LeadContactMethod) {
    if (!canRestore(method, viewer.role)) return setNotice('This method can be restored only by Lead Gen, Manager, or Admin.');
    setMethods((items) => items.map((item) => item.id === method.id ? { ...item, health: 'unverified', focus: 'active', restricted: false } : item));
    if (session && isRemoteCrmId(lead.id) && isRemoteCrmId(method.id)) void restoreRemoteContactMethod(session, lead.id, method.id, { reason: 'Restored for reassignment or renewed outreach.' }).catch((error: unknown) => setNotice(error instanceof Error ? error.message : 'CRM could not restore this contact method.'));
    setNotice(`${method.value} was restored to active contact methods.`);
  }
  function addContact(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const formElement = event.currentTarget; const data = new FormData(formElement); const type = String(data.get('type')) as 'phone' | 'email'; const value = String(data.get('value') ?? '').trim(); const label = String(data.get('label') ?? '').trim() || undefined;
    const validation = validateContactMethod(type, value); if (validation) return setNotice(validation);
    const comparable = type === 'phone' ? value.replace(/\D/g, '') : value.toLowerCase();
    if (methods.some((method) => method.type === type && (type === 'phone' ? method.value.replace(/\D/g, '') : method.value.toLowerCase()) === comparable)) return setNotice('This contact method is already listed.');
    const append = (id: string) => { setMethods((items) => [...items, { id, type, value, label, health: 'unverified', focus: 'active' }]); formElement.reset(); setContactOpen(false); setNotice(`${type === 'email' ? 'Email address' : 'Phone number'} added. It starts as Unverified.`); };
    if (session && isRemoteCrmId(lead.id)) void addRemoteContactMethod(session, lead.id, { methodType: type, value, label }).then((result) => append(result.contactMethodId)).catch((error: unknown) => setNotice(error instanceof Error ? error.message : 'CRM could not add this contact method.'));
    else append(`${lead.id}-${Date.now()}`);
  }
  async function logActivity(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const data = new FormData(event.currentTarget); const methodId = String(data.get('method') ?? ''); const outcome = String(data.get('outcome') ?? ''); const type = String(data.get('type') ?? 'call'); const note = String(data.get('note') ?? '').trim(); const followUpValue = String(data.get('followUpAt') ?? ''); const followUpAction = String(data.get('followUpAction') ?? 'Call') as 'Call' | 'Email' | 'SMS' | 'Task'; const followUpPurpose = String(data.get('followUpPurpose') ?? '').trim(); const method = methods.find((item) => item.id === methodId);
    if (!method) return setNotice('Choose a contact method first.');
    if (!outcome) return setNotice('Choose what happened before saving.');
    if (followUpValue && new Date(followUpValue).getTime() <= Date.now()) return setNotice('Choose a future date and time for the follow-up.');
    const at = new Date().toISOString();
    const followUpAt = followUpValue ? new Date(followUpValue).toISOString() : undefined;
    const remote = Boolean(session && isRemoteCrmId(lead.id) && isRemoteCrmId(method.id));
    if (remote) {
      try {
        await logRemoteSalesActivity(session!, lead.id, { contactMethodId: method.id, type, outcome, body: note || undefined, followUpAt, followUpAction: followUpAt ? followUpAction : undefined, followUpPurpose: followUpAt ? followUpPurpose || undefined : undefined });
      } catch (error) {
        setNotice(error instanceof Error ? error.message : 'CRM could not save this activity.');
        return;
      }
    }
    setHistory((items) => [{ id: `${Date.now()}`, at, type, outcome, method: method.value, note: note || undefined, actorId: viewer.id, followUpAt, followUpPurpose: followUpPurpose || undefined }, ...items]);
    setMethods((items) => items.map((item) => item.id === method.id ? { ...item, lastAttemptAt: at, lastOutcome: outcome } : item));
    if (followUpAt) setFollowUps((items) => [...items, { id: `${lead.id}-follow-up-${Date.now()}`, ownerId: viewer.id, dueAt: followUpAt, action: followUpAction, status: 'open' }]);
    if (outcome === 'connected' || outcome === 'replied' || outcome === 'meeting_booked') onStatus(lead, 'connected', remote ? { persist: false } : undefined);
    setActivityOpen(false); setActivityMethodId(undefined); setNotice(followUpAt ? 'Activity and next follow-up saved together.' : 'Activity logged. Add a next step when more work is required.');
  }
  function openActivity(method?: LeadContactMethod) { setActivityMethodId(method?.id ?? primaryMethod?.id); setActivityOpen(true); }

  return <section className="lead-workspace">
    <header className="lead-workspace-head"><button className="quiet icon-label" onClick={onBack}><IconArrowLeft size={17} /> Lead inbox</button><div><span className="eyebrow">LEAD WORKSPACE</span><h1>{lead.name}</h1><p>{lead.source} · {leadCategoryLabels[lead.category ?? 'not_available']} · Assigned to {workspaceUsers.find((user) => user.id === lead.assignments.find((assignment) => !assignment.endedAt)?.ownerId)?.name ?? 'Unassigned'}</p></div><div className="lead-workspace-head-actions">{canEdit && <button className="quiet icon-label" onClick={() => setEditOpen(true)}><IconEdit size={16} /> Edit lead</button>}<span className={`status ${lead.status}`}>{lead.status.replaceAll('_', ' ')}</span></div></header>
    {notice && <div className="workflow-notice"><IconCircleCheck size={18} />{notice}<button onClick={() => setNotice('')} aria-label="Dismiss"><IconX size={15} /></button></div>}
    <nav className="lead-workspace-tabs"><button className={tab === 'overview' ? 'active' : ''} onClick={() => setTab('overview')}>Overview</button><button className={tab === 'history' ? 'active' : ''} onClick={() => setTab('history')}>Activity history <small>{history.length}</small></button></nav>
    {tab === 'history' ? <ActivityHistory history={history} users={workspaceUsers} onBack={() => setTab('overview')} /> : <>
      <section className={`workflow-card lead-action-center ${nextFollowUp && Date.parse(nextFollowUp.dueAt) < Date.now() ? 'is-overdue' : ''}`}>
        <div className="action-center-copy"><span className="eyebrow">NEXT BEST ACTION</span><h2>{nextFollowUp ? `${nextFollowUp.action} follow-up ${Date.parse(nextFollowUp.dueAt) < Date.now() ? 'is overdue' : 'is scheduled'}` : latestActivity ? 'Continue the conversation' : 'Make the first contact'}</h2><p>{nextFollowUp ? `${format(nextFollowUp.dueAt)}${latestActivity?.note ? ` · Last note: ${latestActivity.note}` : ''}` : latestActivity ? `${outcomeLabels[latestActivity.outcome] ?? latestActivity.outcome.replaceAll('_',' ')}${latestActivity.note ? ` · ${latestActivity.note}` : ''}` : 'Choose the best available contact method, record the outcome, and set the next step.'}</p></div>
        <div className="action-center-contact"><span>Primary contact</span><strong>{primaryMethod ? contactValue(primaryMethod) : 'No usable contact method'}</strong><small>{primaryMethod ? `${primaryMethod.type === 'phone' ? 'Phone' : 'Email'} · ${healthLabel[primaryMethod.health]}` : 'Add a phone or email before outreach.'}</small></div>
        {sales && <div className="action-center-actions"><button className="primary" disabled={!primaryMethod} onClick={() => openActivity(primaryMethod)}>{actionIcon(primaryMethod?.type === 'email' ? 'email' : 'call')} {primaryMethod?.type === 'email' ? 'Log email' : 'Log call'}</button><button className="quiet" disabled={!primaryMethod} onClick={() => openActivity(primaryMethod)}><IconCalendarEvent size={17} /> Log and schedule</button></div>}
        {!sales && <span className="action-center-readonly"><IconHistory size={17} /> Sales activity is read-only in this view</span>}
      </section>
      <div className="lead-workspace-grid action-first-grid">
        <section className="workflow-card contact-summary"><div className="workflow-heading"><div><span className="eyebrow">ACTIVE CONTACTS</span><h2>Who can I contact?</h2><p>Keep useful methods in focus. Mark contact quality without changing the whole lead.</p></div>{canManage && <button className="quiet icon-label" onClick={() => setContactOpen(true)}><IconPlus size={17} /> Add contact</button>}</div>
          <MethodGroup title="Best available methods" methods={active} sales={sales} canManage={canManage} onAssess={assess} onLog={openActivity} />
          {secondary.length > 0 && <MethodGroup title="Secondary methods" methods={secondary} sales={sales} canManage={canManage} onAssess={assess} onLog={openActivity} />}
          <details className="removed-methods"><summary>Removed from active focus ({removed.length}) <small>Incorrect, wrong person, and do-not-contact methods remain visible for audit.</small></summary>{removed.map((method) => <div className="removed-method" key={method.id}><span>{method.type === 'phone' ? <IconPhone size={16} /> : <IconMail size={16} />}</span><div><b>{contactValue(method)}</b><small>{healthLabel[method.health]}{method.restricted ? ' · Globally restricted' : ''}</small></div>{canRestore(method, viewer.role) && <button className="quiet" onClick={() => restore(method)}><IconRefresh size={15} /> Restore</button>}</div>)}</details>
        </section>
        <aside className="lead-workspace-side">
          <section className="workflow-card latest-context"><div className="workflow-heading"><div><span className="eyebrow">LATEST INTERACTION</span><h2>{latestActivity ? outcomeLabels[latestActivity.outcome] ?? latestActivity.outcome.replaceAll('_',' ') : 'No activity yet'}</h2></div><button className="quiet icon-only" onClick={() => setTab('history')} aria-label="Open full activity history"><IconExternalLink size={17} /></button></div>{latestActivity ? <><p>{latestActivity.note || `${latestActivity.type.replaceAll('_',' ')} recorded using ${latestActivity.method ?? 'a contact method'}.`}</p><small>{format(latestActivity.at)} · {workspaceUsers.find((user) => user.id === latestActivity.actorId)?.name ?? 'CRM user'}</small></> : <p>Log the first attempt to start a useful history for the next follow-up and Xaviar.</p>}</section>
          <section className="workflow-card stage-card"><span className="eyebrow">LEAD PROGRESS</span>{sales ? <div className="lead-stage-control"><label>Sales lifecycle</label><select value={lead.status} onChange={(event) => onStatus(lead, event.target.value as Lead['status'])}><option value="assigned">Assigned</option><option value="contacted">Contacted</option><option value="connected">Connected</option><option value="follow_up_required">Follow-up required</option><option value="qualified">Qualified</option><option value="proposal_sent">Proposal sent</option><option value="won">Won</option><option value="lost">Lost</option></select></div> : <p><b>Sales lifecycle:</b> {lead.status.replaceAll('_', ' ')}</p>}
            <div className="lead-stage-control"><label>Qualification</label><select value={lead.qualification} disabled={!sales && !marketingControl} onChange={(event) => onQualification(lead, event.target.value as Lead['qualification'])}>{canCorrectQualification ? <><option value="not_available">Not available</option><option value="mql">MQL</option><option value="sql">SQL</option></> : sales ? <><option value="not_available">Not available</option><option value="sql">SQL</option></> : <><option value="not_available">Not available</option><option value="mql">MQL</option></>}</select></div>
          </section>
          <section className="workflow-card lead-brief"><span className="eyebrow">LEAD BRIEF</span><div><small>Project</small><b>{leadCategoryLabels[lead.category ?? 'not_available']}</b></div><div><small>Source</small><b>{lead.source}</b></div>{lead.description && <div><small>Project description</small><p>{lead.description}</p></div>}{lead.address && <div><small>Location</small><p>{lead.address}</p></div>}{lead.researchSummary && <div className="handoff-context"><small>Marketing handoff</small><p>{lead.researchSummary}</p></div>}{lead.originalDetails && <details><summary>Original request details</summary><p>{lead.originalDetails}</p></details>}</section>
          <section className="workflow-card risk-card"><div className="incorrect-flag-summary"><span><IconFlag size={16} /> Whole-lead flags</span><b>{lead.incorrectReports.length}</b><small>{salesFlagCount} of 3 distinct Sales flags toward Admin review</small>{canFlag && <button className="quiet danger-text" onClick={() => setFlagOpen(true)}>Flag lead as incorrect</button>}{lead.incorrectReports.some((report) => report.reporterId === viewer.id) && <small>Your flag is already recorded.</small>}{lead.routingPaused && <small className="warning">Routing paused for Admin review.</small>}</div>{viewer.role === 'admin' && lead.incorrectReview?.state === 'pending' && <div className="admin-review-actions"><b>Admin Incorrect Review</b><button className="danger" onClick={() => onDecision(lead, 'confirmed_incorrect')}>Confirm incorrect</button><button className="quiet" onClick={() => onDecision(lead, 'rejected')}>Reject flags</button><button className="quiet" onClick={() => onDecision(lead, 'merge_duplicate')}>Merge duplicate</button></div>}</section>
        </aside>
      </div>
      {marketingControl && <section className="workflow-card leadgen-panel"><div><span className="eyebrow">LEAD GEN CONTROL</span><h2>Monitor quality and reassign with context</h2><p>Lead Gen can see every contact method and Sales progress, but cannot create Sales activities or set SQL.</p></div><div className="leadgen-actions"><span><IconCheck size={16} /> {active.length} active</span><span><IconClock size={16} /> {secondary.length} secondary</span><span><IconUser size={16} /> {removed.length} removed</span></div><details><summary>Reassign lead</summary><form className="reassign-mini" onSubmit={(event) => onReassign(lead, event)}><select name="owner" defaultValue=""><option value="" disabled>Choose sales agent</option>{workspaceUsers.filter((user) => user.role === 'sales_agent').map((user) => <option value={user.id} key={user.id}>{user.name}</option>)}</select><select name="visibility" defaultValue="full_context"><option value="full_context">Share full context</option><option value="fresh_start">Fresh working view</option></select><input name="reason" placeholder="Reason for handoff" required /><button className="primary">Reassign</button></form><p className="hint">A fresh working view hides conversations only. It never restores removed or restricted contact methods.</p></details></section>}
    </>}
    {sales && <div className="lead-mobile-actions" aria-label="Lead quick actions"><button disabled={!primaryMethod} onClick={() => openActivity(primaryMethod)}>{actionIcon(primaryMethod?.type === 'email' ? 'email' : 'call')} Contact</button><button disabled={!primaryMethod} onClick={() => openActivity(primaryMethod)}><IconNotes size={17} /> Log</button><button disabled={!primaryMethod} onClick={() => openActivity(primaryMethod)}><IconCalendarEvent size={17} /> Follow-up</button></div>}
    {activityOpen && <ActivityDrawer methods={[...active, ...secondary]} initialMethodId={activityMethodId} onClose={() => { setActivityOpen(false); setActivityMethodId(undefined); }} onSubmit={logActivity} />}
    {contactOpen && <ContactModal onClose={() => setContactOpen(false)} onSubmit={addContact} />}
    {editOpen && <LeadEditModal lead={lead} onClose={() => setEditOpen(false)} onSubmit={(event) => { onEditDetails(lead, event); setEditOpen(false); }} />}
    {flagOpen && <IncorrectFlagModal salesCount={salesFlagCount} role={viewer.role} onClose={() => setFlagOpen(false)} onSubmit={(event) => { onReportIncorrect(lead, event); setFlagOpen(false); }} />}
  </section>;
}

function MethodGroup({ title, methods, sales, canManage, onAssess, onLog }: { title: string; methods: LeadContactMethod[]; sales: boolean; canManage: boolean; onAssess: (method: LeadContactMethod, health: ContactHealth) => void; onLog: (method: LeadContactMethod) => void }) { return <div className="method-group"><h3>{title}</h3>{methods.length ? methods.map((method) => <article className="method-row" key={method.id}><span className={`method-icon ${method.type}`}>{method.type === 'phone' ? <IconPhone size={19} /> : <IconAt size={19} />}</span><div className="method-main"><b>{contactValue(method)}</b><small>{method.label || `${method.type === 'phone' ? 'Phone' : 'Email'} contact`}{method.lastOutcome ? ` · Last: ${outcomeLabels[method.lastOutcome] ?? method.lastOutcome.replaceAll('_',' ')}` : ''}</small></div><span className={`health-chip ${method.health}`}>{healthLabel[method.health]}</span>{sales && <button className="quiet method-log" onClick={() => onLog(method)}>{actionIcon(method.type === 'phone' ? 'call' : 'email')} Log {method.type === 'phone' ? 'call' : 'email'}</button>}{canManage && <label className="method-assess"><span className="sr-only">Update method health</span><select value={method.health} onChange={(event) => onAssess(method, event.target.value as ContactHealth)}><option value="unverified">Update quality</option>{healthOptions.map((health) => <option key={health} value={health}>{healthLabel[health]}</option>)}</select><IconChevronDown size={14} /></label>}</article>) : <p className="empty">No usable contact methods are available.</p>}</div>; }
function ActivityDrawer({ methods, initialMethodId, onClose, onSubmit }: { methods: LeadContactMethod[]; initialMethodId?: string; onClose: () => void; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) {
  const initialMethod = methods.find((method) => method.id === initialMethodId) ?? methods[0];
  const [methodId, setMethodId] = useState(initialMethod?.id ?? '');
  const [type, setType] = useState(initialMethod?.type === 'email' ? 'email' : 'call');
  const [outcome, setOutcome] = useState('');
  const [schedule, setSchedule] = useState(false);
  useEffect(() => { if (['no_answer','voicemail','busy','callback_requested'].includes(outcome)) setSchedule(true); }, [outcome]);
  const method = methods.find((item) => item.id === methodId);
  return <div className="workflow-modal-backdrop" role="presentation"><section className="workflow-drawer activity-drawer" role="dialog" aria-modal="true" aria-label="Log sales activity"><header><div><span className="eyebrow">SALES ACTIVITY</span><h2>Log the result and next step</h2><p>Save the outcome and follow-up together so this lead never loses momentum.</p></div><button type="button" className="quiet" onClick={onClose} aria-label="Close"><IconX /></button></header><form onSubmit={onSubmit}>
    <label>Contact method<select name="method" value={methodId} onChange={(event) => { const next = methods.find((item) => item.id === event.target.value); setMethodId(event.target.value); setType(next?.type === 'email' ? 'email' : 'call'); }} required>{methods.map((item) => <option value={item.id} key={item.id}>{item.type === 'phone' ? 'Phone' : 'Email'} · {contactValue(item)}</option>)}</select></label>
    <div className="selected-contact-preview">{method?.type === 'email' ? <IconMail size={18} /> : <IconPhone size={18} />}<span><b>{method ? contactValue(method) : 'Choose a contact method'}</b><small>{method ? healthLabel[method.health] : 'No contact selected'}</small></span></div>
    <div className="two-fields"><label>Activity<select name="type" value={type} onChange={(event) => setType(event.target.value)}><option value="call">Call</option><option value="sms">SMS</option><option value="email">Email</option><option value="meeting">Meeting</option><option value="note">Note</option></select></label><label>Outcome<select name="outcome" value={outcome} onChange={(event) => setOutcome(event.target.value)} required><option value="" disabled>Select outcome</option><option value="connected">Connected</option><option value="no_answer">No answer</option><option value="voicemail">Voicemail</option><option value="busy">Busy</option><option value="callback_requested">Callback requested</option><option value="email_sent">Email sent</option><option value="replied">Replied</option><option value="meeting_booked">Meeting booked</option><option value="not_interested">Not interested</option><option value="other">Other</option></select></label></div>
    <label>Notes<textarea name="note" rows={4} placeholder="What happened? Add only the context needed for the next conversation." /></label>
    <label className="follow-up-toggle"><input type="checkbox" checked={schedule} onChange={(event) => setSchedule(event.target.checked)} /><span><b>Schedule the next step</b><small>Recommended after no answer, voicemail, busy, or callback requested.</small></span></label>
    {schedule && <fieldset className="follow-up-fields"><legend>Next follow-up</legend><div className="two-fields"><label>Date and time<input name="followUpAt" type="datetime-local" required /></label><label>Action<select name="followUpAction" defaultValue={type === 'email' ? 'Email' : type === 'sms' ? 'SMS' : 'Call'}><option>Call</option><option>Email</option><option>SMS</option><option>Task</option></select></label></div><label>Purpose<input name="followUpPurpose" maxLength={1000} placeholder="What should happen next?" /></label></fieldset>}
    {outcome === 'not_interested' && <p className="activity-guidance warning"><IconFlag size={16} /> Save the activity, then choose the approved loss reason before closing the lead.</p>}
    {['connected','replied','meeting_booked'].includes(outcome) && <p className="activity-guidance success"><IconTargetArrow size={16} /> This outcome will move an early-stage lead to Connected.</p>}
    <div className="drawer-actions"><button type="button" className="quiet" onClick={onClose}>Cancel</button><button className="primary">{schedule ? 'Save activity and follow-up' : 'Save activity'}</button></div></form></section></div>;
}
function ContactModal({ onClose, onSubmit }: { onClose: () => void; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { const [type, setType] = useState<'phone' | 'email'>('phone'); return <div className="workflow-modal-backdrop"><section className="workflow-modal" role="dialog" aria-modal="true" aria-label="Add a contact method"><header><div><span className="eyebrow">CONTACT DETAILS</span><h2>Add a phone or email</h2><p>Select the method first. Validation changes automatically.</p></div><button type="button" className="quiet" onClick={onClose} aria-label="Close"><IconX /></button></header><form onSubmit={onSubmit}><label>Contact type<select name="type" value={type} onChange={(event) => setType(event.target.value as 'phone' | 'email')}><option value="phone">Phone number</option><option value="email">Email address</option></select></label><label>{type === 'email' ? 'Email address' : 'Phone number'}<input name="value" type={type === 'email' ? 'email' : 'tel'} inputMode={type === 'email' ? 'email' : 'tel'} autoComplete={type === 'email' ? 'email' : 'tel'} placeholder={type === 'email' ? 'name@example.com' : '+1 555 123 4567'} required /></label><label>Label <input name="label" placeholder={type === 'email' ? 'Optional, for example Work email' : 'Optional, for example Direct line'} /></label><div className="drawer-actions"><button type="button" className="quiet" onClick={onClose}>Cancel</button><button className="primary">Add {type === 'email' ? 'email' : 'phone'}</button></div></form></section></div>; }
function LeadEditModal({ lead, onClose, onSubmit }: { lead: Lead; onClose: () => void; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { return <div className="workflow-modal-backdrop"><section className="workflow-modal lead-edit-modal" role="dialog" aria-modal="true" aria-label="Edit lead details"><header><div><span className="eyebrow">MARKETING DETAILS</span><h2>Edit lead</h2><p>Sales activity and contact-method history are edited separately.</p></div><button type="button" className="quiet" onClick={onClose} aria-label="Close"><IconX /></button></header><form onSubmit={onSubmit}><label>Lead name<input name="name" defaultValue={lead.name} maxLength={160} required /></label><label>Source<select name="source" defaultValue={lead.source} required>{sourceOptions.map((source) => <option value={source} key={source}>{source}</option>)}</select></label><label>Lead category<select name="category" defaultValue={lead.category ?? 'not_available'} required>{leadCategoryOptions.map((category) => <option value={category} key={category}>{leadCategoryLabels[category]}</option>)}</select></label><label>Description<textarea name="description" defaultValue={lead.description ?? ''} rows={6} maxLength={4000} placeholder="Add the lead request, project needs, background, or other useful context." /></label><div className="drawer-actions"><button type="button" className="quiet" onClick={onClose}>Cancel</button><button className="primary">Save lead</button></div></form></section></div>; }
function IncorrectFlagModal({ salesCount, role, onClose, onSubmit }: { salesCount: number; role: User['role']; onClose: () => void; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) { return <div className="workflow-modal-backdrop"><section className="workflow-modal" role="dialog" aria-modal="true" aria-label="Flag lead as incorrect"><header><div><span className="eyebrow">WHOLE-LEAD REVIEW</span><h2>Flag this lead</h2><p>This is separate from marking one phone or email Incorrect.</p></div><button type="button" className="quiet" onClick={onClose} aria-label="Close"><IconX /></button></header><form onSubmit={onSubmit}><div className="threshold-note"><b>{salesCount} of 3 Sales flags</b><span>{role === 'sales_agent' ? 'Your flag counts toward the automatic Admin review threshold.' : 'Your flag is saved as evidence but does not increase the Sales threshold.'}</span></div><label>Reason<select name="reason" defaultValue="" required><option value="" disabled>Choose reason</option><option>Invalid contact information</option><option>Wrong person or business</option><option>Spam or fake request</option><option>Duplicate contact</option></select></label><label>Evidence (optional)<textarea name="evidence" rows={4} maxLength={3000} placeholder="Explain why the complete lead should be reviewed." /></label><div className="drawer-actions"><button type="button" className="quiet" onClick={onClose}>Cancel</button><button className="danger">Save flag</button></div></form></section></div>; }
function ActivityHistory({ history, users, onBack }: { history: HistoryItem[]; users: User[]; onBack: () => void }) { return <section className="workflow-card activity-history"><div className="workflow-heading"><div><span className="eyebrow">FULL HISTORY</span><h2>Every activity, with context</h2><p>Newest activity first. Outcomes, notes, contact methods, and planned next steps stay together.</p></div><button className="quiet" onClick={onBack}>Back to overview</button></div>{history.length ? <ol>{history.map((item) => <li key={item.id}><span>{actionIcon(item.type)}</span><div className="history-entry"><div><b>{item.type.replaceAll('_',' ')} · {outcomeLabels[item.outcome] ?? item.outcome.replaceAll('_', ' ')}</b><small>{users.find((user) => user.id === item.actorId)?.name ?? 'CRM user'}</small></div>{item.method && <p className="history-method">{item.method}</p>}{item.note && <p>{item.note}</p>}{item.followUpAt && <p className="history-next"><IconCalendarEvent size={15} /> Next: {format(item.followUpAt)}{item.followUpPurpose ? ` · ${item.followUpPurpose}` : ''}</p>}</div><time>{format(item.at)}</time></li>)}</ol> : <div className="history-empty"><IconHistory size={28} /><h3>No sales activity yet</h3><p>The first logged call, message, email, or meeting will appear here.</p></div>}</section>; }
